### ISSUE TITLE
Please help with setup: funds available

### ISSUE THREAD

**Issue by mintoumba** [cooper-lyt/keycloak-phone-provider#17]
I need to get this working, especially the authentication part. I am having troubles doing the setup properly. Happy to support financially if you could spend a few hours guiding me through the process.

**Comment by cooper-lyt** [comment]
#9

**Comment by cooper-lyt** [comment]
Duplicate of #

**Comment by cooper-lyt** [comment]
Duplicate of #9

**Comment by cooper-lyt** [comment]
lyt3131@163.com
