### ISSUE TITLE
about sms register/login flow configuraiton

### ISSUE THREAD

**Issue by nssol-wangchenjun** [cooper-lyt/keycloak-phone-provider#9]
Hi, 
    I checkout the provider and yunxin sms provider and started keyloak in docker successfully.
    But I cannot add the sms register/login flow by following the ReadMe, is there more detail guide about the configuraiton?

Thank you

**Comment by cooper-lyt** [comment]
![image](https://user-images.githubusercontent.com/4219608/105630188-95fbd200-5e82-11eb-8510-6eac4ee0f2f5.png)

![image](https://user-images.githubusercontent.com/4219608/105630194-a8760b80-5e82-11eb-92a6-60b1f8d6a336.png)


![image](https://user-images.githubusercontent.com/4219608/105630130-2f76b400-5e82-11eb-8554-7a462610293d.png)

**Comment by Conrix** [comment]
Hi,
I have tried to set up dummy registration provider. But I can not add an execution named "Registration provider callback". I am on keycloak 12.0.4. I don't have errors in log and didn't find a warning or something else that give me a hint were to look for the reason. 
<img width="1313" alt="Registration" src="https://user-images.githubusercontent.com/7335019/112221116-5d306d00-8c27-11eb-8738-ae85aaf8f9b8.png">
When I call http://mykeycloak.com/auth/realms/myrealm/protocol/openid-connect/registrations?client_id=myclient&response_type=code&scope=openid%20email&redirect_uri=http://myredirect.com I got a "Page not found" error on login page.
Any hints from you side?

**Comment by Varagos** [comment]
Could you also provide a screenshot for direct grant flow? I'm getting an error when validating the code.

**Comment by cooper-lyt** [comment]
Readme is updated.  support Quarkus
